services:
  shop_db:
    image: postgres
    env_file:
      - .postgres.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_shop:/var/lib/postgresql/data

  shop_service:
    build:
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - .env
    depends_on:
      - shop_db
volumes:
  postgres_shop:
